Project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Project.view import login_view, logout_view, home_view

urlpatterns = [
    path('', home_view, name='home'),
    path('admin/', admin.site.urls,name='admin'),
    path('reports/', include('reports.urls', namespace='reports')),
    path('uploads/', include('uploads.urls', namespace='uploads')),
    path('profile/', include('profiles.urls', namespace='profile')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports/urls.py
from django.urls import path

from .views import (
    ReportsListView,
    ReportsDetailView,
    delete_report,
    pdf_export
)

app_name = 'reports'

urlpatterns = [
    path('', ReportsListView.as_view(), name='reports_home'),
    path('<pk>/', ReportsDetailView.as_view(), name='detail'),
    path('<pk>/delete', delete_report, name='delete'),
    path('<pk>/pdf', pdf_export, name='pdf')
]

reports/models.py
from django.utils import timezone

from django.db import models
from django.urls import reverse

from profiles.models import Profile
from uploads.models import Uploads


# Create your models here.

class Report(models.Model):
    name = models.CharField(max_length=120)
    upload = models.ForeignKey(Uploads, on_delete=models.CASCADE)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    remarks = models.TextField(blank=True)
    result = models.TextField(blank=True)
    pred_mean = models.TextField(blank=True)
    face_sample = models.TextField(blank=True)
    no_of_frames = models.IntegerField(blank=True, null=True)
    frame_pred_graph = models.TextField(blank=True)
    frame_graph = models.TextField(blank=True)

    def get_absolute_url(self):
        return reverse('reports:detail', kwargs={'pk': self.pk})

    def get_upload_id(self):
        return self.upload.upload_id

    def get_author_name(self):
        return self.author.get_user_name()

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        if self.created is None:
            self.created = timezone.now()
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ('-created',)

reports/forms.py
from django import forms


class ReportsSearchForm(forms.Form):
    date_from = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    date_to = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        fields = ('search', 'date_from', 'date_to')

reports/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import get_template
from django.views.generic import ListView, DetailView
from xhtml2pdf import pisa
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import ReportsSearchForm
from .models import Report


# Create your views here.
class ReportsListView(LoginRequiredMixin,ListView):
    model = Report
    template_name = 'reports/main.html'

    def get_queryset(self):
        query = self.request.GET.get('search')
        date_from = self.request.GET.get('date_from')
        date_to = self.request.GET.get('date_to')
        reports_qs = Report.objects.all()
        print(query)
        print(date_to)
        print(date_from)
        if query:
            pass
        elif date_from or date_to:
            reports_qs = Report.objects.filter(created__date__lte=date_to, created__date__gte=date_from)
        # Do your filter and search here
        return reports_qs

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['form'] = ReportsSearchForm(initial={
            'search': self.request.GET.get('search', ''),
            'date_from': self.request.GET.get('date_from', ''),
            'date_to': self.request.GET.get('date_from', ''),
        })

        return context


class ReportsDetailView(LoginRequiredMixin,DetailView):
    model = Report
    template_name = 'reports/detail.html'

@login_required()
def delete_report(request, pk):
    print(request.method)
    Report.objects.get(pk=pk).delete()
    return redirect('/reports')

@login_required()
def pdf_export(request, pk):
    template_path = 'reports/pdf.html'
    report = get_object_or_404(Report, pk=pk)
    context = {'object': report}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
        html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

reports/templates/reports/detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    {{ object.name }}
{% endblock title %}

{% block content %}
    <div id="alert-box"></div>
    <div class="card border mb-3" style="min-width: 75%;">
        <div class="card-header">{{ object.name }}</div>
        <div class="card-body">
            <p class="card-title fw-bold">User</p>
            <p class="card-title">{{ object.get_author_name }}</p>
            <p class="card-text">

            <p class="fw-bold">Created</p>
            <p class="fw-normal">
                {{ object.created }} </p>
            <p class="fw-bold">Result</p>
            {% if object.result == 'FAKE' %}
                <p class="text-danger fw-normal">
                    {% else %}
                <p class="text-success fw-normal">
            {% endif %}
            {{ object.result }} </p>
            <p class="fw-bold">Deepfake Probability</p>
            <p class="fw-normal">
                {{ object.pred_mean }} </p>
            <p class="fw-bold">Extracted Face</p>
            <p>
                {% if object.face_sample %}
                    <img src="data:image/png;base64, {{ object.face_sample|safe }}" id='img' class="w-25 img-thumbnail"
                         alt="{{ object.name }}">
                {% endif %} </p>
            <p class="fw-bold">No of Frames Extracted</p>
            <p class="fw-normal">
                {{ object.no_of_frames }} </p>
            <p class="fw-bold">Frame prediction distribution</p>
            <p>
                {% if object.frame_pred_graph %}
                    <img src="data:image/png;base64, {{ object.frame_pred_graph|safe }}" id='img'
                         class="w-50 img-thumbnail"
                         alt="{{ object.name }}">
                {% endif %} </p>
            <p class="fw-bold">Remarks</p>
            <p class="fw-normal">
                {{ object.remarks }} </p>
            </p>
        </div>
    </div>
    <a href="{% url 'reports:delete' object.pk %}" class="card-link">Delete</a>
    <a href="{% url 'reports:pdf' object.pk %}" class="card-link">Save as PDF</a>
{% endblock content %}

reports/templates/reports/main.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% block title %}
    reports
{% endblock title %}

{% block content %}
    {% if no_data %}
        <div class="alert alert-warning" role="alert">
            {{ no_data }}
        </div>
    {% endif %}


    <form class="form-inline mb-3">
        <div class="form-control">{{ form }}<input class="btn-small btn-outline-primary btn-search m-3" type="submit"/></div>
        {% csrf_token %}
    </form>



    </form>
    <div class="row row-cols-1 row-cols-md-4 g-4">

        {% for obj in object_list %}
            <div class="col">
                <div class="card h-100">
                    {% if obj.face_sample %}
                        <img src="data:image/png;base64, {{ obj.face_sample|safe }}" id='img'
                             class="img-thumbnail"
                             alt="{{ obj.name }}">
                    {% else %}
                        <img src="{% static  'report.png' %}" class="card-img-top" alt="{{ obj.name }}">
                    {% endif %}

                    <div class="card-body">
                        <h5 class="card-title">{{ obj.name |truncatewords:5 }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ obj.author }}</h6>
                        <p class="card-text">{{ obj.created }}</p>
                        <a href="{{ obj.get_absolute_url }}" class="card-link">Details</a>
                        <a href="{% url 'reports:pdf' obj.pk %}" class="card-link">Save as PDF</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    </div>


{% endblock content %}

reports/templates/reports/pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ object.name }}</title>
    <style>
        .image1 {
            width: 150px;
            height: auto;
        }
        .image2 {
            width: 400px;
            height: auto;
        }
    </style>
</head>
<body>
<h1>{{ object.name }}</h1>
<p><b>File Name</b><br>{{ object.upload.file_name }}</p>
<p><b>User</b><br>{{ object.get_author_name }}</p>
<p><b>Created</b><br>{{ object.created }}</p>
<p><b>Result</b><br>{{ object.result }} </p>
<p><b>Deepfake Probability</b><br>{{ object.pred_mean }}</p>
<p><b>Extracted Face</b><br><img src="data:image/png;base64, {{ object.face_sample|safe }}" class="image1"></p>
<p><b>No of Frames Extracted</b><br>{{ object.no_of_frames }}</p>
<p><b>Frame prediction distribution</b><br><img src="data:image/png;base64, {{ object.frame_pred_graph|safe }}" class="image2"></p>
<p><b>Remarks</b><br> {{ object.remarks }}</p>
</body>
</html>