Project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Project.view import login_view, logout_view, home_view

urlpatterns = [
    path('', home_view, name='home'),
    path('admin/', admin.site.urls,name='admin'),
    path('reports/', include('reports.urls', namespace='reports')),
    path('uploads/', include('uploads.urls', namespace='uploads')),
    path('profile/', include('profiles.urls', namespace='profile')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from .views import my_profile_view

app_name = 'profiles'

urlpatterns = [
    path('', my_profile_view, name='my')
]

reports/urls.py
from django.urls import path

from .views import (
    ReportsListView,
    ReportsDetailView,
    delete_report,
    pdf_export
)

app_name = 'reports'

urlpatterns = [
    path('', ReportsListView.as_view(), name='reports_home'),
    path('<pk>/', ReportsDetailView.as_view(), name='detail'),
    path('<pk>/delete', delete_report, name='delete'),
    path('<pk>/pdf', pdf_export, name='pdf')
]

uploads/urls.py
from django.urls import path

from .views import (
    upload_view,
    detect_view,
    UploadTemplateView
)

app_name = 'uploads'

urlpatterns = [
    path('generate', upload_view, name='generate'),
    path('upload', UploadTemplateView.as_view(), name='upload'),
    path('report', detect_view, name='report-generate'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}"/>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>

    <!-- Dropzone js -->
    <link rel="stylesheet" href="{% static 'dropzone.css' %}">
    <script src="{% static 'dropzone.js' %}" defer></script>

    <!-- Custom js & css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block scripts %}
    {% endblock scripts %}

    <title>Deepfake Detection | {% block title %}{% endblock title %}</title>
</head>
<body>
{% include 'navbar.html' %}
<div class="container mt-3 mb-3">
    {% block content %}
    {% endblock content %}
</div>

<!-- Bootstrap js -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
{% load static %}
{% url 'home' as path_to_home %}
{% url 'reports:reports_home' as path_to_reports_home %}
{% url 'reports:detail' as path_to_reports_detail %}
{% url 'uploads:upload' as path_to_uploads_home %}
{% url 'profile:my' as path_to_profile_home %}
{% url 'login' as path_to_login %}
{% url 'logout' as path_to_logout %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ path_to_home }}"><img src="{% static 'logo.png' %}" height="80"
                                                               class="logo-sm"></a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_home %} active {% endif %}"
                       href="{{ path_to_home }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link  {% if request.path == path_to_uploads_home %} active {% endif %}"
                       href="{{ path_to_uploads_home }}">Uploads</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link  {% if request.path == path_to_reports_home %} active {% endif %}"
                       href="{{ path_to_reports_home }}">Reports</a>
                </li>
            </ul>
        </div>

        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown m-2 " style="list-style-type: none">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                {{ request.user }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ path_to_profile_home }}">Profile</a>
                <a class="dropdown-item" href="{{ path_to_logout }}">Log out</a>
            </div>
        </li>
        {% endif %}


    </div>
</nav>